### ISSUE TITLE
Parser tests

### ISSUE THREAD

**Issue by MatthiesB** [HAW-MI-P1/FBSearch#7]
Please fix your code in order to pass the newly added/enhanced jUnit tests. Most failures are about missing or wrong exceptions.

**Comment by lukasgr90** [comment]
I'm not able to reproduce the bug.

Starting the test collection (de.haw.AllTests) all of our 20 parser tests are run successful.

**Comment by lukasgr90** [comment]
Ok got it.

**Comment by lukasgr90** [comment]
Should be fixed now.
